### PR TITLE
Fix defocus animation for media view with custom layer mask

### PR DESCRIPTION
**Pull request by vascopinto**
If the media views (`UIImageView`) have some custom layer mask, the defocus animation with elastic becomes wrong.
The problem can be fixed by adding a screenshot from the media view to the `mainImageView` when the defocus animation is about to start.
A new flag was added (`useMediaViewScreenShotOnEndFocusAnimation`) to the `ASMediaFocusManager` to activate this behavior (default is disable).

Maybe You can consider to use the screenshot on defocus animation as default, because it smooths the animations and fix the problem with custom layers.

### CODE REVIEW

**Comment by dogo** [comment]
+1. Awesome patch. I was struggling with this

**Comment by TiagoVeloso** [comment]
will this PR be merged?

**Comment by beloso** [comment]
I've asked @vascopinto to participate on his branch and updated his PR, can this be merged @autresphere ?

**Comment by crsantos** [comment]
🎉

**Comment by crsantos** [comment]
Do you need a PR for the new tag and podspec?

**Comment by autresphere** [comment]
Oh yes please!

**Pull request merged**
